name: Running deployment scripts
run-name: Deploy to plancpills.org

on:
  push:
    branches: [ "master" ]

jobs:
  Deploy-To-BunnyCDN:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'install node modules'
        run: npm install

      - name: 'build netlify static site'
        run: npx netlify build
        env:
          NETLIFY_AUTH_TOKEN: 'aJC1Y41geKZCVZXaQwC1zIVzVO1vE433S-G1CRBA7L4'
          NETLIFY_SITE_ID: '89bb4fa1-ccd5-4f87-9899-19151d5fbac3'

      - name: Deploy to Edge Storage (bunny.net)
        uses: own3d/bunny-action@main
        env:
          BUNNY_API_ACCESS_KEY: 0a3c4a07-2070-4d9f-b880-e029c25391112e4099fa-3ec4-4878-8265-30d3bab64575
          BUNNY_STORAGE_USERNAME: "planc-nearshore"
          BUNNY_STORAGE_PASSWORD: 90cb7785-3953-44e3-ab5cb93012d7-6c1e-41d4
          BUNNY_PULL_ZONE_ID: 1092423
        with:
          args: deploy --dir=public
